version: '3.8'
services:
  chroma:
    image: ghcr.io/chroma-core/chroma:0.4.24
    volumes:
      - chroma-data:/chroma
    ports:
      - "8000:8000"

  astro:
    build: .
    env_file: .env
    ports:
      - "8001:8000"
    depends_on:
      - chroma

volumes:
  chroma-data:
